name: Update YAML File

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Ini akan dijalankan setiap hari pada pukul 00:00 UTC

jobs:
  update-yaml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Modify YAML File
      run: |
        # Menambahkan baris kosong di akhir file
        echo "" >> test_QA-1727163160852.yaml
        # Atau, gunakan sed untuk menambah baris baru setelah baris tertentu (misalnya baris terakhir)
        # sed -i -e '$a\' test_QA-1727163160852.yaml
        
        # Menyiapkan Git untuk commit
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        # Commit perubahan jika ada modifikasi
        if [[ $(git status --porcelain) ]]; then
          git add test_QA-1727163160852.yaml
          git commit -m "Automated edit: added new line to test_QA-1727163160852.yaml"
        fi

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push
