name: Update YAML File

# Menjalankan workflow pada push ke main atau sesuai jadwal (cron)
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Ini akan dijalankan setiap hari pada pukul 00:00 UTC

jobs:
  update-yaml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Modify YAML File
      run: |
        # Tambahkan enter (baris kosong) di akhir file
        echo "" >> .harness/pipelines/test_QA-1727163160852.yaml
        # Atau, Anda bisa menggunakan `sed` untuk menambah baris baru
        # sed -i -e '$a\' .harness/pipelines/test_QA-1727163160852.yaml
        
        # Setup git config
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Commit perubahan jika ada modifikasi
        if [[ $(git status --porcelain) ]]; then
          git add .harness/pipelines/test_QA-1727163160852.yaml
          git commit -m "Automated update: added new line to .harness/pipelines/test_QA-1727163160852.yaml"
        fi

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push
